//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrandingSpec) DeepCopyInto(out *BrandingSpec) {
	*out = *in
	if in.LoginDisclaimer != nil {
		in, out := &in.LoginDisclaimer, &out.LoginDisclaimer
		*out = new(string)
		**out = **in
	}
	if in.CustomCss != nil {
		in, out := &in.CustomCss, &out.CustomCss
		*out = new(string)
		**out = **in
	}
	if in.SplashscreenEnabled != nil {
		in, out := &in.SplashscreenEnabled, &out.SplashscreenEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrandingSpec.
func (in *BrandingSpec) DeepCopy() *BrandingSpec {
	if in == nil {
		return nil
	}
	out := new(BrandingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayReference) DeepCopyInto(out *GatewayReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayReference.
func (in *GatewayReference) DeepCopy() *GatewayReference {
	if in == nil {
		return nil
	}
	out := new(GatewayReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySSO) DeepCopyInto(out *GatewaySSO) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySSO.
func (in *GatewaySSO) DeepCopy() *GatewaySSO {
	if in == nil {
		return nil
	}
	out := new(GatewaySSO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySpec) DeepCopyInto(out *GatewaySpec) {
	*out = *in
	out.GatewayRef = in.GatewayRef
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SSO != nil {
		in, out := &in.SSO, &out.SSO
		*out = new(GatewaySSO)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySpec.
func (in *GatewaySpec) DeepCopy() *GatewaySpec {
	if in == nil {
		return nil
	}
	out := new(GatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneralSpec) DeepCopyInto(out *GeneralSpec) {
	*out = *in
	if in.ServerName != nil {
		in, out := &in.ServerName, &out.ServerName
		*out = new(string)
		**out = **in
	}
	if in.UICulture != nil {
		in, out := &in.UICulture, &out.UICulture
		*out = new(string)
		**out = **in
	}
	if in.QuickConnectAvailable != nil {
		in, out := &in.QuickConnectAvailable, &out.QuickConnectAvailable
		*out = new(bool)
		**out = **in
	}
	if in.EnableMetrics != nil {
		in, out := &in.EnableMetrics, &out.EnableMetrics
		*out = new(bool)
		**out = **in
	}
	if in.EnableNormalizedItemByNameIds != nil {
		in, out := &in.EnableNormalizedItemByNameIds, &out.EnableNormalizedItemByNameIds
		*out = new(bool)
		**out = **in
	}
	if in.AllowClientLogUpload != nil {
		in, out := &in.AllowClientLogUpload, &out.AllowClientLogUpload
		*out = new(bool)
		**out = **in
	}
	if in.EnableSlowResponseWarning != nil {
		in, out := &in.EnableSlowResponseWarning, &out.EnableSlowResponseWarning
		*out = new(bool)
		**out = **in
	}
	if in.SlowResponseThresholdMs != nil {
		in, out := &in.SlowResponseThresholdMs, &out.SlowResponseThresholdMs
		*out = new(int64)
		**out = **in
	}
	if in.LibraryScanFanoutConcurrency != nil {
		in, out := &in.LibraryScanFanoutConcurrency, &out.LibraryScanFanoutConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.LibraryMetadataRefreshConcurrency != nil {
		in, out := &in.LibraryMetadataRefreshConcurrency, &out.LibraryMetadataRefreshConcurrency
		*out = new(int32)
		**out = **in
	}
	if in.ParallelImageEncodingLimit != nil {
		in, out := &in.ParallelImageEncodingLimit, &out.ParallelImageEncodingLimit
		*out = new(int32)
		**out = **in
	}
	if in.ActivityLogRetentionDays != nil {
		in, out := &in.ActivityLogRetentionDays, &out.ActivityLogRetentionDays
		*out = new(int32)
		**out = **in
	}
	if in.LibraryMonitorDelay != nil {
		in, out := &in.LibraryMonitorDelay, &out.LibraryMonitorDelay
		*out = new(int32)
		**out = **in
	}
	if in.LibraryUpdateDuration != nil {
		in, out := &in.LibraryUpdateDuration, &out.LibraryUpdateDuration
		*out = new(int32)
		**out = **in
	}
	if in.InactiveSessionThreshold != nil {
		in, out := &in.InactiveSessionThreshold, &out.InactiveSessionThreshold
		*out = new(int32)
		**out = **in
	}
	if in.LogFileRetentionDays != nil {
		in, out := &in.LogFileRetentionDays, &out.LogFileRetentionDays
		*out = new(int32)
		**out = **in
	}
	if in.CachePath != nil {
		in, out := &in.CachePath, &out.CachePath
		*out = new(string)
		**out = **in
	}
	if in.MetadataPath != nil {
		in, out := &in.MetadataPath, &out.MetadataPath
		*out = new(string)
		**out = **in
	}
	if in.CorsHosts != nil {
		in, out := &in.CorsHosts, &out.CorsHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneralSpec.
func (in *GeneralSpec) DeepCopy() *GeneralSpec {
	if in == nil {
		return nil
	}
	out := new(GeneralSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareAccel) DeepCopyInto(out *HardwareAccel) {
	*out = *in
	if in.RenderGroupGID != nil {
		in, out := &in.RenderGroupGID, &out.RenderGroupGID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareAccel.
func (in *HardwareAccel) DeepCopy() *HardwareAccel {
	if in == nil {
		return nil
	}
	out := new(HardwareAccel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSource) DeepCopyInto(out *ImageSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSource.
func (in *ImageSource) DeepCopy() *ImageSource {
	if in == nil {
		return nil
	}
	out := new(ImageSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(IngressTLS)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTLS) DeepCopyInto(out *IngressTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTLS.
func (in *IngressTLS) DeepCopy() *IngressTLS {
	if in == nil {
		return nil
	}
	out := new(IngressTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceEndpoints) DeepCopyInto(out *InstanceEndpoints) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceEndpoints.
func (in *InstanceEndpoints) DeepCopy() *InstanceEndpoints {
	if in == nil {
		return nil
	}
	out := new(InstanceEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceMediaSelection) DeepCopyInto(out *InstanceMediaSelection) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReadWrite != nil {
		in, out := &in.ReadWrite, &out.ReadWrite
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceMediaSelection.
func (in *InstanceMediaSelection) DeepCopy() *InstanceMediaSelection {
	if in == nil {
		return nil
	}
	out := new(InstanceMediaSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Jellyfin) DeepCopyInto(out *Jellyfin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Jellyfin.
func (in *Jellyfin) DeepCopy() *Jellyfin {
	if in == nil {
		return nil
	}
	out := new(Jellyfin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Jellyfin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinAPISpec) DeepCopyInto(out *JellyfinAPISpec) {
	*out = *in
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinAPISpec.
func (in *JellyfinAPISpec) DeepCopy() *JellyfinAPISpec {
	if in == nil {
		return nil
	}
	out := new(JellyfinAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinList) DeepCopyInto(out *JellyfinList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Jellyfin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinList.
func (in *JellyfinList) DeepCopy() *JellyfinList {
	if in == nil {
		return nil
	}
	out := new(JellyfinList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JellyfinList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinPlugin) DeepCopyInto(out *JellyfinPlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinPlugin.
func (in *JellyfinPlugin) DeepCopy() *JellyfinPlugin {
	if in == nil {
		return nil
	}
	out := new(JellyfinPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JellyfinPlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinPluginList) DeepCopyInto(out *JellyfinPluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JellyfinPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinPluginList.
func (in *JellyfinPluginList) DeepCopy() *JellyfinPluginList {
	if in == nil {
		return nil
	}
	out := new(JellyfinPluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JellyfinPluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinPluginSpec) DeepCopyInto(out *JellyfinPluginSpec) {
	*out = *in
	if in.JellyfinRef != nil {
		in, out := &in.JellyfinRef, &out.JellyfinRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	out.PluginImage = in.PluginImage
	out.Meta = in.Meta
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = new(PluginInstall)
		(*in).DeepCopyInto(*out)
	}
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = make([]PluginWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]PluginService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinPluginSpec.
func (in *JellyfinPluginSpec) DeepCopy() *JellyfinPluginSpec {
	if in == nil {
		return nil
	}
	out := new(JellyfinPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinPluginStatus) DeepCopyInto(out *JellyfinPluginStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinPluginStatus.
func (in *JellyfinPluginStatus) DeepCopy() *JellyfinPluginStatus {
	if in == nil {
		return nil
	}
	out := new(JellyfinPluginStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinSpec) DeepCopyInto(out *JellyfinSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Service.DeepCopyInto(&out.Service)
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Web != nil {
		in, out := &in.Web, &out.Web
		*out = new(WebSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.HardwareAcceleration != nil {
		in, out := &in.HardwareAcceleration, &out.HardwareAcceleration
		*out = new(HardwareAccel)
		(*in).DeepCopyInto(*out)
	}
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = new(JellyfinAPISpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Transcoding != nil {
		in, out := &in.Transcoding, &out.Transcoding
		*out = new(TranscodingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.General != nil {
		in, out := &in.General, &out.General
		*out = new(GeneralSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Branding != nil {
		in, out := &in.Branding, &out.Branding
		*out = new(BrandingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Playback != nil {
		in, out := &in.Playback, &out.Playback
		*out = new(PlaybackSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PluginSelector != nil {
		in, out := &in.PluginSelector, &out.PluginSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinSpec.
func (in *JellyfinSpec) DeepCopy() *JellyfinSpec {
	if in == nil {
		return nil
	}
	out := new(JellyfinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinStatus) DeepCopyInto(out *JellyfinStatus) {
	*out = *in
	out.Endpoints = in.Endpoints
	if in.LoadedPlugins != nil {
		in, out := &in.LoadedPlugins, &out.LoadedPlugins
		*out = make([]LoadedPlugin, len(*in))
		copy(*out, *in)
	}
	if in.ManagedLibraries != nil {
		in, out := &in.ManagedLibraries, &out.ManagedLibraries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinStatus.
func (in *JellyfinStatus) DeepCopy() *JellyfinStatus {
	if in == nil {
		return nil
	}
	out := new(JellyfinStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JellyfinStorage) DeepCopyInto(out *JellyfinStorage) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(PVCSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Media != nil {
		in, out := &in.Media, &out.Media
		*out = make([]MediaFolder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JellyfinStorage.
func (in *JellyfinStorage) DeepCopy() *JellyfinStorage {
	if in == nil {
		return nil
	}
	out := new(JellyfinStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LibrarySpec) DeepCopyInto(out *LibrarySpec) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LibrarySpec.
func (in *LibrarySpec) DeepCopy() *LibrarySpec {
	if in == nil {
		return nil
	}
	out := new(LibrarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadedPlugin) DeepCopyInto(out *LoadedPlugin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadedPlugin.
func (in *LoadedPlugin) DeepCopy() *LoadedPlugin {
	if in == nil {
		return nil
	}
	out := new(LoadedPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaFolder) DeepCopyInto(out *MediaFolder) {
	*out = *in
	if in.NFS != nil {
		in, out := &in.NFS, &out.NFS
		*out = new(NFSSource)
		(*in).DeepCopyInto(*out)
	}
	if in.PVC != nil {
		in, out := &in.PVC, &out.PVC
		*out = new(PVCSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Library != nil {
		in, out := &in.Library, &out.Library
		*out = new(LibrarySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaFolder.
func (in *MediaFolder) DeepCopy() *MediaFolder {
	if in == nil {
		return nil
	}
	out := new(MediaFolder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NFSSource) DeepCopyInto(out *NFSSource) {
	*out = *in
	if in.MountOptions != nil {
		in, out := &in.MountOptions, &out.MountOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NFSSource.
func (in *NFSSource) DeepCopy() *NFSSource {
	if in == nil {
		return nil
	}
	out := new(NFSSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCSpec) DeepCopyInto(out *PVCSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCSpec.
func (in *PVCSpec) DeepCopy() *PVCSpec {
	if in == nil {
		return nil
	}
	out := new(PVCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlaybackSpec) DeepCopyInto(out *PlaybackSpec) {
	*out = *in
	if in.MinResumePct != nil {
		in, out := &in.MinResumePct, &out.MinResumePct
		*out = new(int32)
		**out = **in
	}
	if in.MaxResumePct != nil {
		in, out := &in.MaxResumePct, &out.MaxResumePct
		*out = new(int32)
		**out = **in
	}
	if in.MinResumeDurationSeconds != nil {
		in, out := &in.MinResumeDurationSeconds, &out.MinResumeDurationSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MinAudiobookResumeMinutes != nil {
		in, out := &in.MinAudiobookResumeMinutes, &out.MinAudiobookResumeMinutes
		*out = new(int32)
		**out = **in
	}
	if in.MaxAudiobookResumeMinutes != nil {
		in, out := &in.MaxAudiobookResumeMinutes, &out.MaxAudiobookResumeMinutes
		*out = new(int32)
		**out = **in
	}
	if in.RemoteClientBitrateLimit != nil {
		in, out := &in.RemoteClientBitrateLimit, &out.RemoteClientBitrateLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlaybackSpec.
func (in *PlaybackSpec) DeepCopy() *PlaybackSpec {
	if in == nil {
		return nil
	}
	out := new(PlaybackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginInstall) DeepCopyInto(out *PluginInstall) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(ImageSource)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginInstall.
func (in *PluginInstall) DeepCopy() *PluginInstall {
	if in == nil {
		return nil
	}
	out := new(PluginInstall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginMeta) DeepCopyInto(out *PluginMeta) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginMeta.
func (in *PluginMeta) DeepCopy() *PluginMeta {
	if in == nil {
		return nil
	}
	out := new(PluginMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginService) DeepCopyInto(out *PluginService) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ServicePort, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginService.
func (in *PluginService) DeepCopy() *PluginService {
	if in == nil {
		return nil
	}
	out := new(PluginService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginWorkload) DeepCopyInto(out *PluginWorkload) {
	*out = *in
	out.Image = in.Image
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ContainerPort, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]v1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]v1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InstanceMedia != nil {
		in, out := &in.InstanceMedia, &out.InstanceMedia
		*out = new(InstanceMediaSelection)
		(*in).DeepCopyInto(*out)
	}
	if in.TerminationGracePeriodSeconds != nil {
		in, out := &in.TerminationGracePeriodSeconds, &out.TerminationGracePeriodSeconds
		*out = new(int64)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(WorkloadAutoscaling)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginWorkload.
func (in *PluginWorkload) DeepCopy() *PluginWorkload {
	if in == nil {
		return nil
	}
	out := new(PluginWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SegmentDeletionSpec) DeepCopyInto(out *SegmentDeletionSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.KeepSeconds != nil {
		in, out := &in.KeepSeconds, &out.KeepSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SegmentDeletionSpec.
func (in *SegmentDeletionSpec) DeepCopy() *SegmentDeletionSpec {
	if in == nil {
		return nil
	}
	out := new(SegmentDeletionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThrottleSpec) DeepCopyInto(out *ThrottleSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.DelaySeconds != nil {
		in, out := &in.DelaySeconds, &out.DelaySeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThrottleSpec.
func (in *ThrottleSpec) DeepCopy() *ThrottleSpec {
	if in == nil {
		return nil
	}
	out := new(ThrottleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TranscodingSpec) DeepCopyInto(out *TranscodingSpec) {
	*out = *in
	if in.Throttle != nil {
		in, out := &in.Throttle, &out.Throttle
		*out = new(ThrottleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SegmentDeletion != nil {
		in, out := &in.SegmentDeletion, &out.SegmentDeletion
		*out = new(SegmentDeletionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TranscodingSpec.
func (in *TranscodingSpec) DeepCopy() *TranscodingSpec {
	if in == nil {
		return nil
	}
	out := new(TranscodingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebSpec) DeepCopyInto(out *WebSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Service.DeepCopyInto(&out.Service)
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebSpec.
func (in *WebSpec) DeepCopy() *WebSpec {
	if in == nil {
		return nil
	}
	out := new(WebSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadAutoscaling) DeepCopyInto(out *WorkloadAutoscaling) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadAutoscaling.
func (in *WorkloadAutoscaling) DeepCopy() *WorkloadAutoscaling {
	if in == nil {
		return nil
	}
	out := new(WorkloadAutoscaling)
	in.DeepCopyInto(out)
	return out
}
